'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class magAssegnaOrdini
    
    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout
    
    '''<summary>
    '''comboMagazzinieri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comboMagazzinieri As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''btnFiltra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFiltra As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid As Global.DevExpress.Web.ASPxGridView
End Class
