'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class newcustomerAdd
    
    '''<summary>
    '''lb_cTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_cTitolo As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''ASPxFormLayout_newCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout_newCustomer As Global.DevExpress.Web.ASPxFormLayout
    
    '''<summary>
    '''LayoutItemNestedControlContainer6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer6 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''lb_codiceNewCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_codiceNewCustomer As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''LayoutItemNestedControlContainer7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer7 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''lb_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_username As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''LayoutItemNestedControlContainer8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer8 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''combo_catClienti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_catClienti As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer9 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_name As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_name2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_name2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer10 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''combo_naturaGiuridica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_naturaGiuridica As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer11 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_piva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_piva As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer12 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_codfiscale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_codfiscale As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer13 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_indirizzo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_indirizzo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_indirizzo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_indirizzo2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer17 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_numeroCivico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_numeroCivico As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer14 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''lookupCitta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lookupCitta As Global.DevExpress.Web.ASPxGridLookup
    
    '''<summary>
    '''SqlDataSourceCAPPARIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceCAPPARIO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''LayoutItemNestedControlContainer15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer15 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_CAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_CAP As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer16 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_provincia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_provincia As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer18 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_nazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_nazione As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer19 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_telefono1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_telefono1 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer21 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_telefono2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_telefono2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer20 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_fax As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer22 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_email As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_nomeDest1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_nomeDest1 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_nomeDest2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_nomeDest2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''combo_naturagiuridicaDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_naturagiuridicaDest As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''tb_indirizzoDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_indirizzoDest As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_indirizzoDest2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_indirizzoDest2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lookupCittaDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lookupCittaDest As Global.DevExpress.Web.ASPxGridLookup
    
    '''<summary>
    '''SqlDataSourceCAPPARIO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceCAPPARIO2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tb_capDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_capDest As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_provinciaDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_provinciaDest As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer4 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_nazioneDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_nazioneDest As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer5 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_telefonoDest1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_telefonoDest1 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer3 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_telefonoDest2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_telefonoDest2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer2 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_faxDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_faxDest As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer1 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''tb_emailDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_emailDest As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''grigliaPagamenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grigliaPagamenti As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''tb_naz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_naz As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_CD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_CD As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_cin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_cin As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_abi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_abi As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_cab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_cab As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_contocorrente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_contocorrente As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''btn_Salva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Salva As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btn_NuovoOrdine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_NuovoOrdine As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxCallback_saveCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback_saveCustomer As Global.DevExpress.Web.ASPxCallback
    
    '''<summary>
    '''ASPxLoadingPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLoadingPanel2 As Global.DevExpress.Web.ASPxLoadingPanel
    
    '''<summary>
    '''popupEsito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupEsito As Global.DevExpress.Web.ASPxPopupControl
End Class
